### ISSUE TITLE
character movement into vehicle redundant

### ISSUE THREAD

**Issue by lostamongtrees** [RolePlayGateway/roleplaygateway#138]
redundant movements
![image](https://user-images.githubusercontent.com/52435234/61574128-8418c200-aa88-11e9-996b-0509651c6e00.png)

**Comment by lostamongtrees** [comment]
incomplete character movements
![image](https://user-images.githubusercontent.com/52435234/61597371-f4852780-abdd-11e9-8866-d64d3bb22103.png)
she apparently did not make it there!
![image](https://user-images.githubusercontent.com/52435234/61597364-d7505900-abdd-11e9-8175-028c49417412.png)

**Comment by lostamongtrees** [comment]
I think this is fixed, will run through to verify if someone else doesn't get to it first!

**Comment by lostamongtrees** [comment]
Alternatively, no vehicle interactions are being designated

![image](https://user-images.githubusercontent.com/52435234/63986976-4d30c580-caa4-11e9-98cf-ca9023979ccb.png)

![image](https://user-images.githubusercontent.com/52435234/63986992-5de13b80-caa4-11e9-8f7a-90a06a61829a.png)

**Comment by martindale** [comment]
Please verify this still occurs @lostamongtrees / @thaumatology
